### ISSUE TITLE
Conversion to pdf/mobi/txt failed

### ISSUE THREAD

**Issue by zdzis** [wsexport/tool#128] opened 2017-04-23 14:53 UTC
Hello Tpt,
Trying to convert to a format other than ePub (pdf/mobi/txt) fails for some time, e.g.:
https://tools.wmflabs.org/wsexport/tool/book.php?lang=fr&format=pdf-a5&page=La_Science_et_l%E2%80%99Hypoth%C3%A8se
https://tools.wmflabs.org/wsexport/tool/book.php?lang=pl&page=Roztw%C3%B3r+Pytla&format=pdf-a5
> Conversion to pdf failed.,

Regards,

Z.

**Comment by Tpt** [comment] 2017-04-24 14:29
Hello zdzis, this issue seems to be solved now. it was caused by webservice workers not able to fire the grid job that does the conversion

**Comment by zdzis** [comment] 2017-04-24 17:20
thank you, works fine.

**Comment by zdzis** [comment] 2017-04-26 20:16
the same problem since yesterday...

Z.

**Comment by Tpt** [comment] 2017-04-26 22:47
Should be back. I lease this issue open because the root cause of the problem is not solved and so could happen again.

**Comment by samwilson** [comment] 2020-07-29 06:43
Closing as probably-fixed. :-)

If similar issues happen again, please open new tickets on Phabricator. Thanks!

**Closed by samwilson** 2020-07-29 06:43 UTC
