### ISSUE TITLE
Export to rtf, pdf failing on te.wikisource

### ISSUE THREAD

**Issue by arjunaraoc** [wsexport/tool#88] opened 2016-03-17 01:37 UTC
URL for Sample document with links.
https://te.wikisource.org/wiki/%E0%B0%85%E0%B0%AC%E0%B0%A6%E0%B1%8D%E0%B0%A7%E0%B0%BE%E0%B0%B2_%E0%B0%B5%E0%B1%87%E0%B0%9F_-_%E0%B0%A8%E0%B0%BF%E0%B0%9C%E0%B0%BE%E0%B0%B2_%E0%B0%AC%E0%B0%BE%E0%B0%9F

**Comment by jberkel** [comment] 2016-03-17 09:57
Is there an error message? I've just tried the conversion locally and it worked there, see attached pdf.

[అబద్ధాల_వేట_-_నిజాల_బాట.pdf](https://github.com/wsexport/tool/files/177596/_._-_._.pdf)

**Comment by jberkel** [comment] 2016-03-17 10:15
Direct conversion url: https://tools.wmflabs.org/wsexport/tool/book.php?lang=te&format=pdf-a4&page=అబద్ధాల_వేట_-_నిజాల_బాట

I just noticed that the PDF generation is very slow, there are more than 100 sections in the book. Maybe you're experiencing timeouts.

**Comment by arjunaraoc** [comment] 2016-03-17 10:51
Thanks for your quick response. You are right. It took six  minutes. Is there a way to speed up or provide a progress update?

**Comment by jberkel** [comment] 2016-03-17 11:45
The slowness is due to an external tool we use (calibre) so there's not much which can be done to speed it up. Regarding progress updates, this would require some bigger changes to the tool, basically make the whole process asynchronous. Not sure if this is easily doable within the wmflabs infrastructure, maybe somebody else can answer this?

**Comment by chinhkmaht** [comment] 2016-04-08 04:13
can you share library of sms backup

**Comment by Tpt** [comment] 2016-04-13 11:06
As it's not a specific bug but only one related to the current slowness of the tool, I think I can close this issue as duplicate of #97

**Closed by Tpt** 2016-04-13 11:06 UTC
