### ISSUE TITLE
Update embed fonts to their latest version

### ISSUE THREAD

**Issue by Tpt** [wsexport/tool#120] opened 2016-10-16 20:53 UTC
We are still using the 4 years ago version of LinuxLibertine and FreeSerif

**Comment by ousia** [comment] 2016-10-16 21:05
@Tpt, as far as I know _Linux Libertine_ is an abandoned project (it hasn”t been updated in four years. 

_FreeSerif_ is being actively maintained, but hasn’t release an update in four years. I don’t even know whether they have an estimated date for the next release.

So it seems that we are using the latest versions available.

**Comment by Tpt** [comment] 2016-10-16 21:08
Ok, thank you! I keep this issue opened as a reminder if ever one of these projects releases a new version.

**Comment by psubhashish** [comment] 2018-04-07 06:44
Can the Noto fonts be added for the South Asian languages e.g. [Noto Sans Oriya](https://noto-website-2.storage.googleapis.com/pkgs/NotoSansOriya-unhinted.zip) for Odia so that users can embed these fonts while downloading books in different formats. The reason I am requesting this is because many South Asian languages are not pre-installed in all mobile devices. All the Noto fonts are licensed under SIL [Open Font License](http://scripts.sil.org/cms/scripts/page.php?site_id=nrsi&id=OFL) are quite compatible.

**Comment by Tpt** [comment] 2018-04-07 18:26
@psubhashish Thank you for the suggestion. I'm trying to figure out a good way to make all Noto fonts available because I believe that Odia is not the only language that could benefit from them

**Comment by samwilson** [comment] 2020-06-24 00:53
I've got a PR at #230 that makes it possible to use any font installed on the system (which includes NotoSansOriya; 154 Noto font families all up).

**Comment by psubhashish** [comment] 2020-06-25 06:18
<img width="498" alt="Screen Shot 2020-06-25 at 9 56 36 AM" src="https://user-images.githubusercontent.com/1258090/85665961-855f5f80-b6d9-11ea-88b5-de95e227bdfe.png">

The issue is how to enable the use of system fonts when there is no specific option in the [tool](https://wsexport.wmflabs.org/tool/)? I tried to download a PDF version of the title "[ଗଳ୍ପସ୍ଵଳ୍ପ](https://or.wikisource.org/wiki/%E0%AC%97%E0%AC%B3%E0%AD%8D%E0%AC%AA%E0%AC%B8%E0%AD%8D%E0%AC%B5%E0%AC%B3%E0%AD%8D%E0%AC%AA)" from orwikisource and the result is above.

**Comment by samwilson** [comment] 2020-06-25 06:20
Sorry, I should have been clearer: the thing I've been working on is to enable the use of system fonts, but it's not yet been merged into the tool. It's nearly ready for code review though, so hopefully it'll be done soon. Keep an eye on https://phabricator.wikimedia.org/T254918 for more info.

**Comment by samwilson** [comment] 2020-08-05 02:43
Closing this in favour of the above Phab issue.

**Closed by samwilson** 2020-08-05 02:43 UTC
