### ISSUE TITLE
PDF/Epub output not done of sub page of Bengali Wikisource

### ISSUE THREAD

**Issue by jayantanth** [wsexport/tool#62] opened 2015-11-05 16:38 UTC
PDF/Epub output not done of sub page of Bengali Wikisource. You can check it for main page featured article PDF out or from https://bn.wikisource.org/wiki/%E0%A6%9A%E0%A6%BE%E0%A6%81%E0%A6%A6%E0%A7%87%E0%A6%B0_%E0%A6%AA%E0%A6%BE%E0%A6%B9%E0%A6%BE%E0%A6%A1%E0%A6%BC

**Comment by Tpt** [comment] 2015-11-05 18:21
Thank you for the report. But I don't think it is a bug in the export tool. Wsexport is not able to export the subpages of this book because there is no table of content in the main page of this book. I keep this issue opened if you have questions about how wsexport works.

**Comment by jayantanth** [comment] 2015-11-05 18:26
I have tried manually input here https://tools.wmflabs.org/wsexport/tool/book.php, but its not worked.

**Comment by jayantanth** [comment] 2015-11-05 18:27
Also I have reported here https://phabricator.wikimedia.org/T117879

**Comment by Tpt** [comment] 2015-11-05 18:29
As I just said, if there is no link from the body of the main page of the book [1] to the subpages of the book, the export tool is not able to know which subpages should be exported and in which order and, so, do not export them.

[1] https://bn.wikisource.org/wiki/%E0%A6%9A%E0%A6%BE%E0%A6%81%E0%A6%A6%E0%A7%87%E0%A6%B0_%E0%A6%AA%E0%A6%BE%E0%A6%B9%E0%A6%BE%E0%A6%A1%E0%A6%BC

**Comment by jayantanth** [comment] 2015-11-05 18:35
Understand, Is it means this tools have not export full PDF book? Even when I am trying to export  from main page of ENWS feature article "Grab a download!" section https://tools.wmflabs.org/wsexport/tool/book.php?lang=en&format=pdf-a5&page=The+Laws+of+Hammurabi%2C+King+of+Babylonia, its download  zerobyte PDF file.

**Comment by Tpt** [comment] 2015-11-05 19:09
It seems that the compute grid of Wikimedia Tools Labs is down at this moment. The PDF export should be back when the grid will be up again.

**Comment by Tpt** [comment] 2015-11-23 15:32
I believe that the issue is fixed now. Fell free to open again this bug if it is not the case.

**Closed by Tpt** 2015-11-23 15:32 UTC
